backend:
  name: github
  repo: keep-network/tbtc-website
  site_domain: tbtc.network
  base_url: https://backend.tbtc.network/
  auth_endpoint: netlify/auth

site_url: https://tbtc.network

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - name: "news-item"
    label: "News"
    folder: "src/pages/news"
    extension: "md"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "news/{{slug}}"
    fields:
      - {label: "Template Key", name: "template", widget: "hidden", default: "news-item"}
      - {label: "Path", name: "path", widget: "hidden"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list", required: false}

  - name: "resource"
    label: "Resources"
    folder: "src/pages/developers"
    extension: "md"
    create: true
    slug: "{{slug}}"
    preview_path: "developers/{{slug}}"
    fields:
      - {label: "Template Key", name: "template", widget: "hidden", default: "resource"}
      - {label: "Path", name: "path", widget: "hidden"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Heading", name: "heading", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "template", widget: "hidden", default: "home-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/"}
          - {label: "Title", name: "title", widget: "string"}
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Subtitle", name: "subtitle", widget: "string"}
              - label: "Buttons"
                name: "buttons"
                widget: "list"
                fields: [
                  {label: "Text", name: "text", widget: "string"},
                  {label: "Url", name: "url", widget: "string"}
                ]
                allow_add: false
          - label: "Features"
            name: "features"
            widget: "list"
            fields:
              - {label: "title", name: "title", widget: "string"}
              - {label: "description", name: "description", widget: "string"}
          - label: "Spotlight 1"
            name: "spotlight_1"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Side Label", name: "label", widget: "string"}
              - {label: "Body", name: "body", widget: "markdown", required: false}
              - label: "Button Link"
                name: "button"
                widget: "object"
                required: false
                fields: [
                  {label: "Text", name: "text", widget: "string"},
                  {label: "Url", name: "url", widget: "string"}
                ]
          - label: "Spotlight 2"
            name: "spotlight_2"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Side Label", name: "label", widget: "string"}
              - {label: "Body", name: "body", widget: "markdown", required: false}
              - label: "Button Link"
                name: "button"
                widget: "object"
                required: false
                fields: [
                  {label: "Text", name: "text", widget: "string"},
                  {label: "Url", name: "url", widget: "string"}
                ]
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "template", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Supporters"
            name: "supporters"
            widget: "list"
            fields: [
              {label: "Name", name: "name", widget: "string"},
              {label: "Description", name: "description", widget: "string"},
              {label: "Url", name: "url", widget: "string"}
            ]
      - file: "src/pages/developers/index.md"
        label: "Developers"
        name: "developers"
        fields:
          - {label: "Template Key", name: "template", widget: "hidden", default: "developers-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/developers"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/faq/index.md"
        label: "FAQ"
        name: "faq"
        fields:
          - {label: "Template Key", name: "template", widget: "hidden", default: "faq-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/faq"}
          - {label: "Title", name: "title", widget: "string"}
          - label: "Questions"
            name: "questions"
            widget: "list"
            fields: [
              {label: "Question", name: "question", widget: "string"},
              {label: "Answer", name: "answer", widget: "markdown"}
            ]

  - name: "header_and_footer"
    label: "Header & Footer"
    files:
      - file: "src/pages/announcement/index.md"
        label: "Announcement Banner"
        name: "announcement"
        fields:
          - {label: "Template Key", name: "template", widget: "hidden", default: "announcement"}
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown", required: false, minimal: true}
